[domain_controllers]
dc01 ansible_host=10.10.10.10
dc02 ansible_host=10.10.10.11

[domain_controllers:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
